// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: actor_web.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strconv "strconv"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ConfigType int32

const (
	CONFIG_OK     ConfigType = 0
	CONFIG_GAMES  ConfigType = 1
	CONFIG_ENV    ConfigType = 2
	CONFIG_NOTICE ConfigType = 3
	CONFIG_SHOP   ConfigType = 4
	CONFIG_VIP    ConfigType = 5
	CONFIG_TASK   ConfigType = 6
	CONFIG_LOGIN  ConfigType = 7
)

var ConfigType_name = map[int32]string{
	0: "CONFIG_OK",
	1: "CONFIG_GAMES",
	2: "CONFIG_ENV",
	3: "CONFIG_NOTICE",
	4: "CONFIG_SHOP",
	5: "CONFIG_VIP",
	6: "CONFIG_TASK",
	7: "CONFIG_LOGIN",
}
var ConfigType_value = map[string]int32{
	"CONFIG_OK":     0,
	"CONFIG_GAMES":  1,
	"CONFIG_ENV":    2,
	"CONFIG_NOTICE": 3,
	"CONFIG_SHOP":   4,
	"CONFIG_VIP":    5,
	"CONFIG_TASK":   6,
	"CONFIG_LOGIN":  7,
}

func (ConfigType) EnumDescriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{0} }

type ConfigAtype int32

const (
	CONFIG_UPSERT ConfigAtype = 0
	CONFIG_DELETE ConfigAtype = 1
)

var ConfigAtype_name = map[int32]string{
	0: "CONFIG_UPSERT",
	1: "CONFIG_DELETE",
}
var ConfigAtype_value = map[string]int32{
	"CONFIG_UPSERT": 0,
	"CONFIG_DELETE": 1,
}

func (ConfigAtype) EnumDescriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{1} }

type WebCode int32

const (
	WebReqMsg WebCode = 0
	WebOnline WebCode = 1
	WebNotice WebCode = 2
	WebBuild  WebCode = 3
	WebGive   WebCode = 4
	WebShop   WebCode = 5
	WebEnv    WebCode = 6
	WebGame   WebCode = 7
	WebVip    WebCode = 8
	WebNumber WebCode = 9
	WebTask   WebCode = 10
	WebLogin  WebCode = 11
)

var WebCode_name = map[int32]string{
	0:  "WebReqMsg",
	1:  "WebOnline",
	2:  "WebNotice",
	3:  "WebBuild",
	4:  "WebGive",
	5:  "WebShop",
	6:  "WebEnv",
	7:  "WebGame",
	8:  "WebVip",
	9:  "WebNumber",
	10: "WebTask",
	11: "WebLogin",
}
var WebCode_value = map[string]int32{
	"WebReqMsg": 0,
	"WebOnline": 1,
	"WebNotice": 2,
	"WebBuild":  3,
	"WebGive":   4,
	"WebShop":   5,
	"WebEnv":    6,
	"WebGame":   7,
	"WebVip":    8,
	"WebNumber": 9,
	"WebTask":   10,
	"WebLogin":  11,
}

func (WebCode) EnumDescriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{2} }

// 同步数据
type SyncConfig struct {
	Type  ConfigType  `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.ConfigType" json:"Type,omitempty"`
	Atype ConfigAtype `protobuf:"varint,2,opt,name=Atype,proto3,enum=pb.ConfigAtype" json:"Atype,omitempty"`
	Data  []byte      `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *SyncConfig) Reset()                    { *m = SyncConfig{} }
func (*SyncConfig) ProtoMessage()               {}
func (*SyncConfig) Descriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{0} }

func (m *SyncConfig) GetType() ConfigType {
	if m != nil {
		return m.Type
	}
	return CONFIG_OK
}

func (m *SyncConfig) GetAtype() ConfigAtype {
	if m != nil {
		return m.Atype
	}
	return CONFIG_UPSERT
}

func (m *SyncConfig) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// TODO 主动获取数据
type GetConfig struct {
	Type ConfigType `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.ConfigType" json:"Type,omitempty"`
}

func (m *GetConfig) Reset()                    { *m = GetConfig{} }
func (*GetConfig) ProtoMessage()               {}
func (*GetConfig) Descriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{1} }

func (m *GetConfig) GetType() ConfigType {
	if m != nil {
		return m.Type
	}
	return CONFIG_OK
}

// web请求
type WebRequest struct {
	Code  WebCode     `protobuf:"varint,1,opt,name=Code,proto3,enum=pb.WebCode" json:"Code,omitempty"`
	Atype ConfigAtype `protobuf:"varint,2,opt,name=Atype,proto3,enum=pb.ConfigAtype" json:"Atype,omitempty"`
	Data  []byte      `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *WebRequest) Reset()                    { *m = WebRequest{} }
func (*WebRequest) ProtoMessage()               {}
func (*WebRequest) Descriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{2} }

func (m *WebRequest) GetCode() WebCode {
	if m != nil {
		return m.Code
	}
	return WebReqMsg
}

func (m *WebRequest) GetAtype() ConfigAtype {
	if m != nil {
		return m.Atype
	}
	return CONFIG_UPSERT
}

func (m *WebRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type WebResponse struct {
	Code    WebCode `protobuf:"varint,1,opt,name=Code,proto3,enum=pb.WebCode" json:"Code,omitempty"`
	ErrCode int32   `protobuf:"varint,2,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg  string  `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Result  []byte  `protobuf:"bytes,4,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (m *WebResponse) Reset()                    { *m = WebResponse{} }
func (*WebResponse) ProtoMessage()               {}
func (*WebResponse) Descriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{3} }

func (m *WebResponse) GetCode() WebCode {
	if m != nil {
		return m.Code
	}
	return WebReqMsg
}

func (m *WebResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *WebResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *WebResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

// result字符串格式响应
type WebRequest2 struct {
	Code  WebCode     `protobuf:"varint,1,opt,name=Code,proto3,enum=pb.WebCode" json:"Code,omitempty"`
	Atype ConfigAtype `protobuf:"varint,2,opt,name=Atype,proto3,enum=pb.ConfigAtype" json:"Atype,omitempty"`
	Data  string      `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *WebRequest2) Reset()                    { *m = WebRequest2{} }
func (*WebRequest2) ProtoMessage()               {}
func (*WebRequest2) Descriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{4} }

func (m *WebRequest2) GetCode() WebCode {
	if m != nil {
		return m.Code
	}
	return WebReqMsg
}

func (m *WebRequest2) GetAtype() ConfigAtype {
	if m != nil {
		return m.Atype
	}
	return CONFIG_UPSERT
}

func (m *WebRequest2) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type WebResponse2 struct {
	Code    WebCode `protobuf:"varint,1,opt,name=Code,proto3,enum=pb.WebCode" json:"Code,omitempty"`
	ErrCode int32   `protobuf:"varint,2,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg  string  `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Result  string  `protobuf:"bytes,4,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (m *WebResponse2) Reset()                    { *m = WebResponse2{} }
func (*WebResponse2) ProtoMessage()               {}
func (*WebResponse2) Descriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{5} }

func (m *WebResponse2) GetCode() WebCode {
	if m != nil {
		return m.Code
	}
	return WebReqMsg
}

func (m *WebResponse2) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *WebResponse2) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *WebResponse2) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// web请求
type GetNumber struct {
}

func (m *GetNumber) Reset()                    { *m = GetNumber{} }
func (*GetNumber) ProtoMessage()               {}
func (*GetNumber) Descriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{6} }

type GotNumber struct {
	Robot []string `protobuf:"bytes,1,rep,name=Robot" json:"Robot,omitempty"`
	Role  []string `protobuf:"bytes,2,rep,name=Role" json:"Role,omitempty"`
}

func (m *GotNumber) Reset()                    { *m = GotNumber{} }
func (*GotNumber) ProtoMessage()               {}
func (*GotNumber) Descriptor() ([]byte, []int) { return fileDescriptorActorWeb, []int{7} }

func (m *GotNumber) GetRobot() []string {
	if m != nil {
		return m.Robot
	}
	return nil
}

func (m *GotNumber) GetRole() []string {
	if m != nil {
		return m.Role
	}
	return nil
}

func init() {
	proto.RegisterType((*SyncConfig)(nil), "pb.SyncConfig")
	proto.RegisterType((*GetConfig)(nil), "pb.GetConfig")
	proto.RegisterType((*WebRequest)(nil), "pb.WebRequest")
	proto.RegisterType((*WebResponse)(nil), "pb.WebResponse")
	proto.RegisterType((*WebRequest2)(nil), "pb.WebRequest2")
	proto.RegisterType((*WebResponse2)(nil), "pb.WebResponse2")
	proto.RegisterType((*GetNumber)(nil), "pb.GetNumber")
	proto.RegisterType((*GotNumber)(nil), "pb.GotNumber")
	proto.RegisterEnum("pb.ConfigType", ConfigType_name, ConfigType_value)
	proto.RegisterEnum("pb.ConfigAtype", ConfigAtype_name, ConfigAtype_value)
	proto.RegisterEnum("pb.WebCode", WebCode_name, WebCode_value)
}
func (x ConfigType) String() string {
	s, ok := ConfigType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x ConfigAtype) String() string {
	s, ok := ConfigAtype_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x WebCode) String() string {
	s, ok := WebCode_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *SyncConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SyncConfig)
	if !ok {
		that2, ok := that.(SyncConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Atype != that1.Atype {
		return false
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return false
	}
	return true
}
func (this *GetConfig) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetConfig)
	if !ok {
		that2, ok := that.(GetConfig)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	return true
}
func (this *WebRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WebRequest)
	if !ok {
		that2, ok := that.(WebRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.Atype != that1.Atype {
		return false
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return false
	}
	return true
}
func (this *WebResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WebResponse)
	if !ok {
		that2, ok := that.(WebResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.ErrCode != that1.ErrCode {
		return false
	}
	if this.ErrMsg != that1.ErrMsg {
		return false
	}
	if !bytes.Equal(this.Result, that1.Result) {
		return false
	}
	return true
}
func (this *WebRequest2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WebRequest2)
	if !ok {
		that2, ok := that.(WebRequest2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.Atype != that1.Atype {
		return false
	}
	if this.Data != that1.Data {
		return false
	}
	return true
}
func (this *WebResponse2) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*WebResponse2)
	if !ok {
		that2, ok := that.(WebResponse2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.ErrCode != that1.ErrCode {
		return false
	}
	if this.ErrMsg != that1.ErrMsg {
		return false
	}
	if this.Result != that1.Result {
		return false
	}
	return true
}
func (this *GetNumber) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetNumber)
	if !ok {
		that2, ok := that.(GetNumber)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *GotNumber) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GotNumber)
	if !ok {
		that2, ok := that.(GotNumber)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Robot) != len(that1.Robot) {
		return false
	}
	for i := range this.Robot {
		if this.Robot[i] != that1.Robot[i] {
			return false
		}
	}
	if len(this.Role) != len(that1.Role) {
		return false
	}
	for i := range this.Role {
		if this.Role[i] != that1.Role[i] {
			return false
		}
	}
	return true
}
func (this *SyncConfig) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&pb.SyncConfig{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Atype: "+fmt.Sprintf("%#v", this.Atype)+",\n")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetConfig) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&pb.GetConfig{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *WebRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&pb.WebRequest{")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "Atype: "+fmt.Sprintf("%#v", this.Atype)+",\n")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *WebResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&pb.WebResponse{")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "ErrCode: "+fmt.Sprintf("%#v", this.ErrCode)+",\n")
	s = append(s, "ErrMsg: "+fmt.Sprintf("%#v", this.ErrMsg)+",\n")
	s = append(s, "Result: "+fmt.Sprintf("%#v", this.Result)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *WebRequest2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&pb.WebRequest2{")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "Atype: "+fmt.Sprintf("%#v", this.Atype)+",\n")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *WebResponse2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&pb.WebResponse2{")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "ErrCode: "+fmt.Sprintf("%#v", this.ErrCode)+",\n")
	s = append(s, "ErrMsg: "+fmt.Sprintf("%#v", this.ErrMsg)+",\n")
	s = append(s, "Result: "+fmt.Sprintf("%#v", this.Result)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetNumber) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&pb.GetNumber{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GotNumber) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&pb.GotNumber{")
	s = append(s, "Robot: "+fmt.Sprintf("%#v", this.Robot)+",\n")
	s = append(s, "Role: "+fmt.Sprintf("%#v", this.Role)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringActorWeb(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *SyncConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Type))
	}
	if m.Atype != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Atype))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *GetConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetConfig) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Type))
	}
	return i, nil
}

func (m *WebRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Code))
	}
	if m.Atype != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Atype))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *WebResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Code))
	}
	if m.ErrCode != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.ErrCode))
	}
	if len(m.ErrMsg) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(len(m.ErrMsg)))
		i += copy(dAtA[i:], m.ErrMsg)
	}
	if len(m.Result) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(len(m.Result)))
		i += copy(dAtA[i:], m.Result)
	}
	return i, nil
}

func (m *WebRequest2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebRequest2) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Code))
	}
	if m.Atype != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Atype))
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *WebResponse2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebResponse2) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Code != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.Code))
	}
	if m.ErrCode != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(m.ErrCode))
	}
	if len(m.ErrMsg) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(len(m.ErrMsg)))
		i += copy(dAtA[i:], m.ErrMsg)
	}
	if len(m.Result) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintActorWeb(dAtA, i, uint64(len(m.Result)))
		i += copy(dAtA[i:], m.Result)
	}
	return i, nil
}

func (m *GetNumber) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetNumber) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *GotNumber) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GotNumber) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Robot) > 0 {
		for _, s := range m.Robot {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.Role) > 0 {
		for _, s := range m.Role {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func encodeVarintActorWeb(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *SyncConfig) Size() (n int) {
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovActorWeb(uint64(m.Type))
	}
	if m.Atype != 0 {
		n += 1 + sovActorWeb(uint64(m.Atype))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovActorWeb(uint64(l))
	}
	return n
}

func (m *GetConfig) Size() (n int) {
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovActorWeb(uint64(m.Type))
	}
	return n
}

func (m *WebRequest) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovActorWeb(uint64(m.Code))
	}
	if m.Atype != 0 {
		n += 1 + sovActorWeb(uint64(m.Atype))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovActorWeb(uint64(l))
	}
	return n
}

func (m *WebResponse) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovActorWeb(uint64(m.Code))
	}
	if m.ErrCode != 0 {
		n += 1 + sovActorWeb(uint64(m.ErrCode))
	}
	l = len(m.ErrMsg)
	if l > 0 {
		n += 1 + l + sovActorWeb(uint64(l))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovActorWeb(uint64(l))
	}
	return n
}

func (m *WebRequest2) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovActorWeb(uint64(m.Code))
	}
	if m.Atype != 0 {
		n += 1 + sovActorWeb(uint64(m.Atype))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovActorWeb(uint64(l))
	}
	return n
}

func (m *WebResponse2) Size() (n int) {
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovActorWeb(uint64(m.Code))
	}
	if m.ErrCode != 0 {
		n += 1 + sovActorWeb(uint64(m.ErrCode))
	}
	l = len(m.ErrMsg)
	if l > 0 {
		n += 1 + l + sovActorWeb(uint64(l))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovActorWeb(uint64(l))
	}
	return n
}

func (m *GetNumber) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *GotNumber) Size() (n int) {
	var l int
	_ = l
	if len(m.Robot) > 0 {
		for _, s := range m.Robot {
			l = len(s)
			n += 1 + l + sovActorWeb(uint64(l))
		}
	}
	if len(m.Role) > 0 {
		for _, s := range m.Role {
			l = len(s)
			n += 1 + l + sovActorWeb(uint64(l))
		}
	}
	return n
}

func sovActorWeb(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozActorWeb(x uint64) (n int) {
	return sovActorWeb(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *SyncConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SyncConfig{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Atype:` + fmt.Sprintf("%v", this.Atype) + `,`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetConfig) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetConfig{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`}`,
	}, "")
	return s
}
func (this *WebRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&WebRequest{`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`Atype:` + fmt.Sprintf("%v", this.Atype) + `,`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`}`,
	}, "")
	return s
}
func (this *WebResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&WebResponse{`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`ErrCode:` + fmt.Sprintf("%v", this.ErrCode) + `,`,
		`ErrMsg:` + fmt.Sprintf("%v", this.ErrMsg) + `,`,
		`Result:` + fmt.Sprintf("%v", this.Result) + `,`,
		`}`,
	}, "")
	return s
}
func (this *WebRequest2) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&WebRequest2{`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`Atype:` + fmt.Sprintf("%v", this.Atype) + `,`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`}`,
	}, "")
	return s
}
func (this *WebResponse2) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&WebResponse2{`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`ErrCode:` + fmt.Sprintf("%v", this.ErrCode) + `,`,
		`ErrMsg:` + fmt.Sprintf("%v", this.ErrMsg) + `,`,
		`Result:` + fmt.Sprintf("%v", this.Result) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetNumber) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetNumber{`,
		`}`,
	}, "")
	return s
}
func (this *GotNumber) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GotNumber{`,
		`Robot:` + fmt.Sprintf("%v", this.Robot) + `,`,
		`Role:` + fmt.Sprintf("%v", this.Role) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringActorWeb(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *SyncConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (ConfigType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Atype", wireType)
			}
			m.Atype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Atype |= (ConfigAtype(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActorWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (ConfigType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActorWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (WebCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Atype", wireType)
			}
			m.Atype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Atype |= (ConfigAtype(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActorWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (WebCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result[:0], dAtA[iNdEx:postIndex]...)
			if m.Result == nil {
				m.Result = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActorWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebRequest2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebRequest2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebRequest2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (WebCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Atype", wireType)
			}
			m.Atype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Atype |= (ConfigAtype(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActorWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebResponse2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebResponse2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebResponse2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (WebCode(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActorWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetNumber) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetNumber: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetNumber: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipActorWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GotNumber) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GotNumber: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GotNumber: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Robot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Robot = append(m.Robot, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorWeb
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Role = append(m.Role, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActorWeb(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorWeb
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActorWeb(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActorWeb
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActorWeb
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthActorWeb
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowActorWeb
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipActorWeb(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthActorWeb = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActorWeb   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("actor_web.proto", fileDescriptorActorWeb) }

var fileDescriptorActorWeb = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x30,
	0x18, 0x8e, 0xdb, 0xb4, 0x5d, 0xfe, 0x74, 0x9b, 0xb1, 0x10, 0xea, 0x29, 0x4c, 0x91, 0x90, 0xa6,
	0x09, 0x15, 0xa9, 0x13, 0x0f, 0xd0, 0x75, 0x21, 0x54, 0x6b, 0x93, 0xca, 0x09, 0xed, 0x71, 0x6a,
	0x3a, 0xd3, 0x45, 0xeb, 0xe2, 0x90, 0xa4, 0x83, 0xde, 0x78, 0x04, 0x0e, 0x3c, 0x04, 0x17, 0xde,
	0x83, 0xe3, 0x8e, 0x1c, 0x69, 0xb8, 0x70, 0xdc, 0x23, 0xa0, 0xb8, 0x2e, 0xcb, 0x0d, 0x24, 0xb4,
	0x9b, 0xbf, 0xef, 0xff, 0xfe, 0xff, 0xf3, 0x67, 0x5b, 0x86, 0xfd, 0xe9, 0x2c, 0xe3, 0xc9, 0xf9,
	0x7b, 0x16, 0xb4, 0xe3, 0x84, 0x67, 0x9c, 0x54, 0xe2, 0xc0, 0xbc, 0x02, 0xf0, 0x56, 0xd1, 0xac,
	0xc7, 0xa3, 0xb7, 0xe1, 0x9c, 0x98, 0xa0, 0xfa, 0xab, 0x98, 0xb5, 0xd0, 0x01, 0x3a, 0xdc, 0xeb,
	0xec, 0xb5, 0xe3, 0xa0, 0xbd, 0xa9, 0x14, 0x2c, 0x15, 0x35, 0xf2, 0x0c, 0x6a, 0xdd, 0xac, 0x10,
	0x55, 0x84, 0x68, 0xff, 0x5e, 0x24, 0x68, 0xba, 0xa9, 0x12, 0x02, 0xea, 0xe9, 0x34, 0x9b, 0xb6,
	0xaa, 0x07, 0xe8, 0xb0, 0x49, 0xc5, 0xda, 0x7c, 0x01, 0x9a, 0xcd, 0xb2, 0x7f, 0xf7, 0x32, 0x2f,
	0x01, 0x26, 0x2c, 0xa0, 0xec, 0xdd, 0x92, 0xa5, 0x19, 0x79, 0x0a, 0x6a, 0x8f, 0x5f, 0x6c, 0x3b,
	0xf4, 0xa2, 0x63, 0xc2, 0x82, 0x82, 0xa2, 0xa2, 0xf0, 0x3f, 0x5b, 0xfb, 0x00, 0xba, 0x70, 0x4a,
	0x63, 0x1e, 0xa5, 0xec, 0xef, 0x56, 0x2d, 0x68, 0x58, 0x49, 0x22, 0x34, 0x85, 0x59, 0x8d, 0x6e,
	0x21, 0x79, 0x02, 0x75, 0x2b, 0x49, 0x86, 0xe9, 0x5c, 0xcc, 0xd7, 0xa8, 0x44, 0x05, 0x4f, 0x59,
	0xba, 0x5c, 0x64, 0x2d, 0x55, 0xf8, 0x4a, 0x64, 0x86, 0xd2, 0x59, 0x64, 0xec, 0x3c, 0x48, 0x48,
	0x4d, 0x86, 0x5c, 0x41, 0xb3, 0x14, 0xb2, 0xf3, 0xf0, 0x29, 0xb5, 0x3f, 0x29, 0x75, 0x71, 0xf5,
	0xce, 0xf2, 0x3a, 0x60, 0x89, 0xf9, 0x12, 0x34, 0x9b, 0x4b, 0x40, 0x1e, 0x43, 0x8d, 0xf2, 0x80,
	0x67, 0x2d, 0x74, 0x50, 0x3d, 0xd4, 0xe8, 0x06, 0x14, 0xdb, 0xa7, 0x7c, 0x51, 0xd8, 0x16, 0xa4,
	0x58, 0x1f, 0x7d, 0x46, 0x00, 0xf7, 0x4f, 0x84, 0xec, 0x82, 0xd6, 0x73, 0x9d, 0x57, 0x7d, 0xfb,
	0xdc, 0x3d, 0xc3, 0x0a, 0xc1, 0xd0, 0x94, 0xd0, 0xee, 0x0e, 0x2d, 0x0f, 0x23, 0xb2, 0x07, 0x20,
	0x19, 0xcb, 0x19, 0xe3, 0x0a, 0x79, 0x04, 0xbb, 0x12, 0x3b, 0xae, 0xdf, 0xef, 0x59, 0xb8, 0x4a,
	0xf6, 0x41, 0x97, 0x94, 0xf7, 0xda, 0x1d, 0x61, 0xb5, 0xd4, 0x33, 0xee, 0x8f, 0x70, 0xad, 0x24,
	0xf0, 0xbb, 0xde, 0x19, 0xae, 0x97, 0x6c, 0x06, 0xae, 0xdd, 0x77, 0x70, 0xe3, 0xe8, 0x18, 0xf4,
	0xd2, 0xf9, 0x97, 0x5c, 0xde, 0x8c, 0x3c, 0x8b, 0xfa, 0x58, 0x29, 0x51, 0xa7, 0xd6, 0xc0, 0xf2,
	0x2d, 0x8c, 0x8e, 0xbe, 0x22, 0x68, 0xc8, 0xb3, 0x2e, 0x82, 0x6c, 0x5e, 0xc0, 0x30, 0x9d, 0x63,
	0x45, 0x42, 0x37, 0x5a, 0x84, 0x11, 0xc3, 0x48, 0x42, 0x87, 0x67, 0xe1, 0x8c, 0xe1, 0x0a, 0x69,
	0xc2, 0xce, 0x84, 0x05, 0x27, 0xcb, 0x70, 0x71, 0x81, 0xab, 0x44, 0x17, 0x53, 0xec, 0xf0, 0x86,
	0x61, 0x55, 0x02, 0xef, 0x92, 0xc7, 0xb8, 0x46, 0x00, 0xea, 0x13, 0x16, 0x58, 0xd1, 0x0d, 0xae,
	0x6f, 0x55, 0xd3, 0x6b, 0x86, 0x1b, 0xb2, 0x30, 0x0e, 0x63, 0xbc, 0xb3, 0x9d, 0x2d, 0x2e, 0x02,
	0x6b, 0x52, 0xe7, 0x4f, 0xd3, 0x2b, 0x0c, 0xd2, 0x68, 0xc0, 0xe7, 0x61, 0x84, 0xf5, 0x93, 0xe7,
	0xb7, 0x6b, 0x43, 0xf9, 0xbe, 0x36, 0x94, 0xbb, 0xb5, 0x81, 0x3e, 0xe6, 0x06, 0xfa, 0x92, 0x1b,
	0xe8, 0x5b, 0x6e, 0xa0, 0xdb, 0xdc, 0x40, 0x3f, 0x72, 0x03, 0xfd, 0xca, 0x0d, 0xe5, 0x2e, 0x37,
	0xd0, 0xa7, 0x9f, 0x86, 0x12, 0xd4, 0xc5, 0x07, 0x73, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x53,
	0x2a, 0xfd, 0xbe, 0x73, 0x04, 0x00, 0x00,
}
