// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: actor_robot.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 机器人消息
type RobotMsg struct {
	Code   string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Num    uint32 `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	Rtype  int32  `protobuf:"varint,3,opt,name=Rtype,proto3" json:"Rtype,omitempty"`
	Ltype  int32  `protobuf:"varint,4,opt,name=Ltype,proto3" json:"Ltype,omitempty"`
	Roomid string `protobuf:"bytes,5,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	EnvBet int32  `protobuf:"varint,6,opt,name=EnvBet,proto3" json:"EnvBet,omitempty"`
}

func (m *RobotMsg) Reset()                    { *m = RobotMsg{} }
func (*RobotMsg) ProtoMessage()               {}
func (*RobotMsg) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{0} }

func (m *RobotMsg) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RobotMsg) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *RobotMsg) GetRtype() int32 {
	if m != nil {
		return m.Rtype
	}
	return 0
}

func (m *RobotMsg) GetLtype() int32 {
	if m != nil {
		return m.Ltype
	}
	return 0
}

func (m *RobotMsg) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

func (m *RobotMsg) GetEnvBet() int32 {
	if m != nil {
		return m.EnvBet
	}
	return 0
}

type RobotLogin struct {
	Phone  string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Roomid string `protobuf:"bytes,2,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	Ltype  int32  `protobuf:"varint,3,opt,name=Ltype,proto3" json:"Ltype,omitempty"`
}

func (m *RobotLogin) Reset()                    { *m = RobotLogin{} }
func (*RobotLogin) ProtoMessage()               {}
func (*RobotLogin) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{1} }

func (m *RobotLogin) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RobotLogin) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

func (m *RobotLogin) GetLtype() int32 {
	if m != nil {
		return m.Ltype
	}
	return 0
}

type RobotReLogin struct {
	Phone  string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Code   string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Rtype  int32  `protobuf:"varint,3,opt,name=Rtype,proto3" json:"Rtype,omitempty"`
	Ltype  int32  `protobuf:"varint,4,opt,name=Ltype,proto3" json:"Ltype,omitempty"`
	Roomid string `protobuf:"bytes,5,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	EnvBet int32  `protobuf:"varint,6,opt,name=EnvBet,proto3" json:"EnvBet,omitempty"`
}

func (m *RobotReLogin) Reset()                    { *m = RobotReLogin{} }
func (*RobotReLogin) ProtoMessage()               {}
func (*RobotReLogin) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{2} }

func (m *RobotReLogin) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RobotReLogin) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RobotReLogin) GetRtype() int32 {
	if m != nil {
		return m.Rtype
	}
	return 0
}

func (m *RobotReLogin) GetLtype() int32 {
	if m != nil {
		return m.Ltype
	}
	return 0
}

func (m *RobotReLogin) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

func (m *RobotReLogin) GetEnvBet() int32 {
	if m != nil {
		return m.EnvBet
	}
	return 0
}

type RobotLogout struct {
	Phone  string `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Code   string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Roomid string `protobuf:"bytes,3,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	Chip   int64  `protobuf:"varint,4,opt,name=Chip,proto3" json:"Chip,omitempty"`
}

func (m *RobotLogout) Reset()                    { *m = RobotLogout{} }
func (*RobotLogout) ProtoMessage()               {}
func (*RobotLogout) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{3} }

func (m *RobotLogout) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RobotLogout) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RobotLogout) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

func (m *RobotLogout) GetChip() int64 {
	if m != nil {
		return m.Chip
	}
	return 0
}

type RobotStop struct {
}

func (m *RobotStop) Reset()                    { *m = RobotStop{} }
func (*RobotStop) ProtoMessage()               {}
func (*RobotStop) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{4} }

type RobotRoomList struct {
	Rtype  int32  `protobuf:"varint,1,opt,name=Rtype,proto3" json:"Rtype,omitempty"`
	Ltype  int32  `protobuf:"varint,2,opt,name=Ltype,proto3" json:"Ltype,omitempty"`
	Roomid string `protobuf:"bytes,3,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
}

func (m *RobotRoomList) Reset()                    { *m = RobotRoomList{} }
func (*RobotRoomList) ProtoMessage()               {}
func (*RobotRoomList) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{5} }

func (m *RobotRoomList) GetRtype() int32 {
	if m != nil {
		return m.Rtype
	}
	return 0
}

func (m *RobotRoomList) GetLtype() int32 {
	if m != nil {
		return m.Ltype
	}
	return 0
}

func (m *RobotRoomList) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

type RobotEnterRoom struct {
	Rtype  int32  `protobuf:"varint,1,opt,name=Rtype,proto3" json:"Rtype,omitempty"`
	Ltype  int32  `protobuf:"varint,2,opt,name=Ltype,proto3" json:"Ltype,omitempty"`
	Roomid string `protobuf:"bytes,3,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	Phone  string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
}

func (m *RobotEnterRoom) Reset()                    { *m = RobotEnterRoom{} }
func (*RobotEnterRoom) ProtoMessage()               {}
func (*RobotEnterRoom) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{6} }

func (m *RobotEnterRoom) GetRtype() int32 {
	if m != nil {
		return m.Rtype
	}
	return 0
}

func (m *RobotEnterRoom) GetLtype() int32 {
	if m != nil {
		return m.Ltype
	}
	return 0
}

func (m *RobotEnterRoom) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

func (m *RobotEnterRoom) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

// 分配人数
type RobotAllot struct {
	Type   uint32 `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	EnvBet int32  `protobuf:"varint,2,opt,name=EnvBet,proto3" json:"EnvBet,omitempty"`
}

func (m *RobotAllot) Reset()                    { *m = RobotAllot{} }
func (*RobotAllot) ProtoMessage()               {}
func (*RobotAllot) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{7} }

func (m *RobotAllot) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *RobotAllot) GetEnvBet() int32 {
	if m != nil {
		return m.EnvBet
	}
	return 0
}

// 虚假人数
type RobotFake struct {
	Roomid  string `protobuf:"bytes,1,opt,name=Roomid,proto3" json:"Roomid,omitempty"`
	RealNum uint32 `protobuf:"varint,2,opt,name=RealNum,proto3" json:"RealNum,omitempty"`
	FakeNum uint32 `protobuf:"varint,3,opt,name=FakeNum,proto3" json:"FakeNum,omitempty"`
	Ltype   int32  `protobuf:"varint,4,opt,name=Ltype,proto3" json:"Ltype,omitempty"`
	Type    uint32 `protobuf:"varint,5,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (m *RobotFake) Reset()                    { *m = RobotFake{} }
func (*RobotFake) ProtoMessage()               {}
func (*RobotFake) Descriptor() ([]byte, []int) { return fileDescriptorActorRobot, []int{8} }

func (m *RobotFake) GetRoomid() string {
	if m != nil {
		return m.Roomid
	}
	return ""
}

func (m *RobotFake) GetRealNum() uint32 {
	if m != nil {
		return m.RealNum
	}
	return 0
}

func (m *RobotFake) GetFakeNum() uint32 {
	if m != nil {
		return m.FakeNum
	}
	return 0
}

func (m *RobotFake) GetLtype() int32 {
	if m != nil {
		return m.Ltype
	}
	return 0
}

func (m *RobotFake) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*RobotMsg)(nil), "pb.RobotMsg")
	proto.RegisterType((*RobotLogin)(nil), "pb.RobotLogin")
	proto.RegisterType((*RobotReLogin)(nil), "pb.RobotReLogin")
	proto.RegisterType((*RobotLogout)(nil), "pb.RobotLogout")
	proto.RegisterType((*RobotStop)(nil), "pb.RobotStop")
	proto.RegisterType((*RobotRoomList)(nil), "pb.RobotRoomList")
	proto.RegisterType((*RobotEnterRoom)(nil), "pb.RobotEnterRoom")
	proto.RegisterType((*RobotAllot)(nil), "pb.RobotAllot")
	proto.RegisterType((*RobotFake)(nil), "pb.RobotFake")
}
func (this *RobotMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotMsg)
	if !ok {
		that2, ok := that.(RobotMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.Num != that1.Num {
		return false
	}
	if this.Rtype != that1.Rtype {
		return false
	}
	if this.Ltype != that1.Ltype {
		return false
	}
	if this.Roomid != that1.Roomid {
		return false
	}
	if this.EnvBet != that1.EnvBet {
		return false
	}
	return true
}
func (this *RobotLogin) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotLogin)
	if !ok {
		that2, ok := that.(RobotLogin)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Phone != that1.Phone {
		return false
	}
	if this.Roomid != that1.Roomid {
		return false
	}
	if this.Ltype != that1.Ltype {
		return false
	}
	return true
}
func (this *RobotReLogin) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotReLogin)
	if !ok {
		that2, ok := that.(RobotReLogin)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Phone != that1.Phone {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.Rtype != that1.Rtype {
		return false
	}
	if this.Ltype != that1.Ltype {
		return false
	}
	if this.Roomid != that1.Roomid {
		return false
	}
	if this.EnvBet != that1.EnvBet {
		return false
	}
	return true
}
func (this *RobotLogout) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotLogout)
	if !ok {
		that2, ok := that.(RobotLogout)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Phone != that1.Phone {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.Roomid != that1.Roomid {
		return false
	}
	if this.Chip != that1.Chip {
		return false
	}
	return true
}
func (this *RobotStop) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotStop)
	if !ok {
		that2, ok := that.(RobotStop)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *RobotRoomList) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotRoomList)
	if !ok {
		that2, ok := that.(RobotRoomList)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Rtype != that1.Rtype {
		return false
	}
	if this.Ltype != that1.Ltype {
		return false
	}
	if this.Roomid != that1.Roomid {
		return false
	}
	return true
}
func (this *RobotEnterRoom) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotEnterRoom)
	if !ok {
		that2, ok := that.(RobotEnterRoom)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Rtype != that1.Rtype {
		return false
	}
	if this.Ltype != that1.Ltype {
		return false
	}
	if this.Roomid != that1.Roomid {
		return false
	}
	if this.Phone != that1.Phone {
		return false
	}
	return true
}
func (this *RobotAllot) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotAllot)
	if !ok {
		that2, ok := that.(RobotAllot)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.EnvBet != that1.EnvBet {
		return false
	}
	return true
}
func (this *RobotFake) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RobotFake)
	if !ok {
		that2, ok := that.(RobotFake)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Roomid != that1.Roomid {
		return false
	}
	if this.RealNum != that1.RealNum {
		return false
	}
	if this.FakeNum != that1.FakeNum {
		return false
	}
	if this.Ltype != that1.Ltype {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	return true
}
func (this *RobotMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&pb.RobotMsg{")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "Num: "+fmt.Sprintf("%#v", this.Num)+",\n")
	s = append(s, "Rtype: "+fmt.Sprintf("%#v", this.Rtype)+",\n")
	s = append(s, "Ltype: "+fmt.Sprintf("%#v", this.Ltype)+",\n")
	s = append(s, "Roomid: "+fmt.Sprintf("%#v", this.Roomid)+",\n")
	s = append(s, "EnvBet: "+fmt.Sprintf("%#v", this.EnvBet)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotLogin) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&pb.RobotLogin{")
	s = append(s, "Phone: "+fmt.Sprintf("%#v", this.Phone)+",\n")
	s = append(s, "Roomid: "+fmt.Sprintf("%#v", this.Roomid)+",\n")
	s = append(s, "Ltype: "+fmt.Sprintf("%#v", this.Ltype)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotReLogin) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&pb.RobotReLogin{")
	s = append(s, "Phone: "+fmt.Sprintf("%#v", this.Phone)+",\n")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "Rtype: "+fmt.Sprintf("%#v", this.Rtype)+",\n")
	s = append(s, "Ltype: "+fmt.Sprintf("%#v", this.Ltype)+",\n")
	s = append(s, "Roomid: "+fmt.Sprintf("%#v", this.Roomid)+",\n")
	s = append(s, "EnvBet: "+fmt.Sprintf("%#v", this.EnvBet)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotLogout) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&pb.RobotLogout{")
	s = append(s, "Phone: "+fmt.Sprintf("%#v", this.Phone)+",\n")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "Roomid: "+fmt.Sprintf("%#v", this.Roomid)+",\n")
	s = append(s, "Chip: "+fmt.Sprintf("%#v", this.Chip)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotStop) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&pb.RobotStop{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotRoomList) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&pb.RobotRoomList{")
	s = append(s, "Rtype: "+fmt.Sprintf("%#v", this.Rtype)+",\n")
	s = append(s, "Ltype: "+fmt.Sprintf("%#v", this.Ltype)+",\n")
	s = append(s, "Roomid: "+fmt.Sprintf("%#v", this.Roomid)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotEnterRoom) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&pb.RobotEnterRoom{")
	s = append(s, "Rtype: "+fmt.Sprintf("%#v", this.Rtype)+",\n")
	s = append(s, "Ltype: "+fmt.Sprintf("%#v", this.Ltype)+",\n")
	s = append(s, "Roomid: "+fmt.Sprintf("%#v", this.Roomid)+",\n")
	s = append(s, "Phone: "+fmt.Sprintf("%#v", this.Phone)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotAllot) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&pb.RobotAllot{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "EnvBet: "+fmt.Sprintf("%#v", this.EnvBet)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RobotFake) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&pb.RobotFake{")
	s = append(s, "Roomid: "+fmt.Sprintf("%#v", this.Roomid)+",\n")
	s = append(s, "RealNum: "+fmt.Sprintf("%#v", this.RealNum)+",\n")
	s = append(s, "FakeNum: "+fmt.Sprintf("%#v", this.FakeNum)+",\n")
	s = append(s, "Ltype: "+fmt.Sprintf("%#v", this.Ltype)+",\n")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringActorRobot(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *RobotMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Code) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Code)))
		i += copy(dAtA[i:], m.Code)
	}
	if m.Num != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Num))
	}
	if m.Rtype != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Rtype))
	}
	if m.Ltype != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Ltype))
	}
	if len(m.Roomid) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Roomid)))
		i += copy(dAtA[i:], m.Roomid)
	}
	if m.EnvBet != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.EnvBet))
	}
	return i, nil
}

func (m *RobotLogin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotLogin) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Phone) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Phone)))
		i += copy(dAtA[i:], m.Phone)
	}
	if len(m.Roomid) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Roomid)))
		i += copy(dAtA[i:], m.Roomid)
	}
	if m.Ltype != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Ltype))
	}
	return i, nil
}

func (m *RobotReLogin) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotReLogin) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Phone) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Phone)))
		i += copy(dAtA[i:], m.Phone)
	}
	if len(m.Code) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Code)))
		i += copy(dAtA[i:], m.Code)
	}
	if m.Rtype != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Rtype))
	}
	if m.Ltype != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Ltype))
	}
	if len(m.Roomid) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Roomid)))
		i += copy(dAtA[i:], m.Roomid)
	}
	if m.EnvBet != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.EnvBet))
	}
	return i, nil
}

func (m *RobotLogout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotLogout) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Phone) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Phone)))
		i += copy(dAtA[i:], m.Phone)
	}
	if len(m.Code) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Code)))
		i += copy(dAtA[i:], m.Code)
	}
	if len(m.Roomid) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Roomid)))
		i += copy(dAtA[i:], m.Roomid)
	}
	if m.Chip != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Chip))
	}
	return i, nil
}

func (m *RobotStop) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotStop) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *RobotRoomList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotRoomList) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Rtype != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Rtype))
	}
	if m.Ltype != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Ltype))
	}
	if len(m.Roomid) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Roomid)))
		i += copy(dAtA[i:], m.Roomid)
	}
	return i, nil
}

func (m *RobotEnterRoom) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotEnterRoom) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Rtype != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Rtype))
	}
	if m.Ltype != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Ltype))
	}
	if len(m.Roomid) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Roomid)))
		i += copy(dAtA[i:], m.Roomid)
	}
	if len(m.Phone) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Phone)))
		i += copy(dAtA[i:], m.Phone)
	}
	return i, nil
}

func (m *RobotAllot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotAllot) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Type))
	}
	if m.EnvBet != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.EnvBet))
	}
	return i, nil
}

func (m *RobotFake) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RobotFake) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Roomid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(len(m.Roomid)))
		i += copy(dAtA[i:], m.Roomid)
	}
	if m.RealNum != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.RealNum))
	}
	if m.FakeNum != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.FakeNum))
	}
	if m.Ltype != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Ltype))
	}
	if m.Type != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintActorRobot(dAtA, i, uint64(m.Type))
	}
	return i, nil
}

func encodeVarintActorRobot(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RobotMsg) Size() (n int) {
	var l int
	_ = l
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	if m.Num != 0 {
		n += 1 + sovActorRobot(uint64(m.Num))
	}
	if m.Rtype != 0 {
		n += 1 + sovActorRobot(uint64(m.Rtype))
	}
	if m.Ltype != 0 {
		n += 1 + sovActorRobot(uint64(m.Ltype))
	}
	l = len(m.Roomid)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	if m.EnvBet != 0 {
		n += 1 + sovActorRobot(uint64(m.EnvBet))
	}
	return n
}

func (m *RobotLogin) Size() (n int) {
	var l int
	_ = l
	l = len(m.Phone)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	l = len(m.Roomid)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	if m.Ltype != 0 {
		n += 1 + sovActorRobot(uint64(m.Ltype))
	}
	return n
}

func (m *RobotReLogin) Size() (n int) {
	var l int
	_ = l
	l = len(m.Phone)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	if m.Rtype != 0 {
		n += 1 + sovActorRobot(uint64(m.Rtype))
	}
	if m.Ltype != 0 {
		n += 1 + sovActorRobot(uint64(m.Ltype))
	}
	l = len(m.Roomid)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	if m.EnvBet != 0 {
		n += 1 + sovActorRobot(uint64(m.EnvBet))
	}
	return n
}

func (m *RobotLogout) Size() (n int) {
	var l int
	_ = l
	l = len(m.Phone)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	l = len(m.Roomid)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	if m.Chip != 0 {
		n += 1 + sovActorRobot(uint64(m.Chip))
	}
	return n
}

func (m *RobotStop) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *RobotRoomList) Size() (n int) {
	var l int
	_ = l
	if m.Rtype != 0 {
		n += 1 + sovActorRobot(uint64(m.Rtype))
	}
	if m.Ltype != 0 {
		n += 1 + sovActorRobot(uint64(m.Ltype))
	}
	l = len(m.Roomid)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	return n
}

func (m *RobotEnterRoom) Size() (n int) {
	var l int
	_ = l
	if m.Rtype != 0 {
		n += 1 + sovActorRobot(uint64(m.Rtype))
	}
	if m.Ltype != 0 {
		n += 1 + sovActorRobot(uint64(m.Ltype))
	}
	l = len(m.Roomid)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	l = len(m.Phone)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	return n
}

func (m *RobotAllot) Size() (n int) {
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovActorRobot(uint64(m.Type))
	}
	if m.EnvBet != 0 {
		n += 1 + sovActorRobot(uint64(m.EnvBet))
	}
	return n
}

func (m *RobotFake) Size() (n int) {
	var l int
	_ = l
	l = len(m.Roomid)
	if l > 0 {
		n += 1 + l + sovActorRobot(uint64(l))
	}
	if m.RealNum != 0 {
		n += 1 + sovActorRobot(uint64(m.RealNum))
	}
	if m.FakeNum != 0 {
		n += 1 + sovActorRobot(uint64(m.FakeNum))
	}
	if m.Ltype != 0 {
		n += 1 + sovActorRobot(uint64(m.Ltype))
	}
	if m.Type != 0 {
		n += 1 + sovActorRobot(uint64(m.Type))
	}
	return n
}

func sovActorRobot(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozActorRobot(x uint64) (n int) {
	return sovActorRobot(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *RobotMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotMsg{`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`Num:` + fmt.Sprintf("%v", this.Num) + `,`,
		`Rtype:` + fmt.Sprintf("%v", this.Rtype) + `,`,
		`Ltype:` + fmt.Sprintf("%v", this.Ltype) + `,`,
		`Roomid:` + fmt.Sprintf("%v", this.Roomid) + `,`,
		`EnvBet:` + fmt.Sprintf("%v", this.EnvBet) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotLogin) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotLogin{`,
		`Phone:` + fmt.Sprintf("%v", this.Phone) + `,`,
		`Roomid:` + fmt.Sprintf("%v", this.Roomid) + `,`,
		`Ltype:` + fmt.Sprintf("%v", this.Ltype) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotReLogin) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotReLogin{`,
		`Phone:` + fmt.Sprintf("%v", this.Phone) + `,`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`Rtype:` + fmt.Sprintf("%v", this.Rtype) + `,`,
		`Ltype:` + fmt.Sprintf("%v", this.Ltype) + `,`,
		`Roomid:` + fmt.Sprintf("%v", this.Roomid) + `,`,
		`EnvBet:` + fmt.Sprintf("%v", this.EnvBet) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotLogout) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotLogout{`,
		`Phone:` + fmt.Sprintf("%v", this.Phone) + `,`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`Roomid:` + fmt.Sprintf("%v", this.Roomid) + `,`,
		`Chip:` + fmt.Sprintf("%v", this.Chip) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotStop) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotStop{`,
		`}`,
	}, "")
	return s
}
func (this *RobotRoomList) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotRoomList{`,
		`Rtype:` + fmt.Sprintf("%v", this.Rtype) + `,`,
		`Ltype:` + fmt.Sprintf("%v", this.Ltype) + `,`,
		`Roomid:` + fmt.Sprintf("%v", this.Roomid) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotEnterRoom) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotEnterRoom{`,
		`Rtype:` + fmt.Sprintf("%v", this.Rtype) + `,`,
		`Ltype:` + fmt.Sprintf("%v", this.Ltype) + `,`,
		`Roomid:` + fmt.Sprintf("%v", this.Roomid) + `,`,
		`Phone:` + fmt.Sprintf("%v", this.Phone) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotAllot) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotAllot{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`EnvBet:` + fmt.Sprintf("%v", this.EnvBet) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RobotFake) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RobotFake{`,
		`Roomid:` + fmt.Sprintf("%v", this.Roomid) + `,`,
		`RealNum:` + fmt.Sprintf("%v", this.RealNum) + `,`,
		`FakeNum:` + fmt.Sprintf("%v", this.FakeNum) + `,`,
		`Ltype:` + fmt.Sprintf("%v", this.Ltype) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringActorRobot(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *RobotMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rtype", wireType)
			}
			m.Rtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rtype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltype", wireType)
			}
			m.Ltype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ltype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roomid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roomid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnvBet", wireType)
			}
			m.EnvBet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnvBet |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotLogin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotLogin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotLogin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roomid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roomid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltype", wireType)
			}
			m.Ltype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ltype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotReLogin) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotReLogin: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotReLogin: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rtype", wireType)
			}
			m.Rtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rtype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltype", wireType)
			}
			m.Ltype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ltype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roomid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roomid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnvBet", wireType)
			}
			m.EnvBet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnvBet |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotLogout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotLogout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotLogout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roomid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roomid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chip", wireType)
			}
			m.Chip = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Chip |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotStop) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotStop: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotStop: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotRoomList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotRoomList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotRoomList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rtype", wireType)
			}
			m.Rtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rtype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltype", wireType)
			}
			m.Ltype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ltype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roomid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roomid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotEnterRoom) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotEnterRoom: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotEnterRoom: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rtype", wireType)
			}
			m.Rtype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rtype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltype", wireType)
			}
			m.Ltype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ltype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roomid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roomid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotAllot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotAllot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotAllot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnvBet", wireType)
			}
			m.EnvBet = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EnvBet |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RobotFake) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RobotFake: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RobotFake: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Roomid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActorRobot
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Roomid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RealNum", wireType)
			}
			m.RealNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RealNum |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FakeNum", wireType)
			}
			m.FakeNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FakeNum |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ltype", wireType)
			}
			m.Ltype = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ltype |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipActorRobot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthActorRobot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActorRobot(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActorRobot
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActorRobot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthActorRobot
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowActorRobot
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipActorRobot(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthActorRobot = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActorRobot   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("actor_robot.proto", fileDescriptorActorRobot) }

var fileDescriptorActorRobot = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x3d, 0x4f, 0xf2, 0x50,
	0x14, 0xee, 0x69, 0x29, 0xef, 0xcb, 0x41, 0x8c, 0x36, 0xc6, 0x74, 0xba, 0x21, 0x9d, 0x18, 0x8c,
	0x8b, 0x8b, 0xab, 0x18, 0x9c, 0xd0, 0x90, 0x8b, 0xbb, 0xe1, 0xa3, 0x81, 0x2a, 0xf4, 0x34, 0xe5,
	0x62, 0xe2, 0xa6, 0xbb, 0x83, 0x83, 0x3f, 0xc2, 0x9f, 0xe2, 0xc8, 0xe8, 0x28, 0x75, 0x71, 0xe4,
	0x27, 0x98, 0x7b, 0xdb, 0xda, 0x36, 0x41, 0x13, 0x13, 0xdd, 0xce, 0x73, 0xee, 0xed, 0xf3, 0x95,
	0x5b, 0xdc, 0xee, 0x0d, 0x04, 0x85, 0x17, 0x21, 0xf5, 0x49, 0xec, 0x07, 0x21, 0x09, 0xb2, 0xf4,
	0xa0, 0xef, 0xdc, 0x03, 0xfe, 0xe7, 0x72, 0x77, 0x3a, 0x1b, 0x59, 0x16, 0x96, 0x8e, 0x69, 0xe8,
	0xda, 0x50, 0x87, 0x46, 0x85, 0xab, 0xd9, 0xda, 0x42, 0xe3, 0x6c, 0x3e, 0xb5, 0xf5, 0x3a, 0x34,
	0x6a, 0x5c, 0x8e, 0xd6, 0x0e, 0x9a, 0x5c, 0xdc, 0x04, 0xae, 0x6d, 0xd4, 0xa1, 0x61, 0xf2, 0x18,
	0xc8, 0x6d, 0x5b, 0x6d, 0x4b, 0xf1, 0x56, 0x01, 0x6b, 0x17, 0xcb, 0x9c, 0x68, 0xea, 0x0d, 0x6d,
	0x53, 0x71, 0x26, 0x48, 0xee, 0x5b, 0xfe, 0x75, 0xd3, 0x15, 0x76, 0x59, 0x5d, 0x4f, 0x90, 0xd3,
	0x41, 0x54, 0x6e, 0xda, 0x34, 0xf2, 0x7c, 0xc9, 0xd9, 0x19, 0x93, 0x9f, 0x1a, 0x8a, 0x41, 0x8e,
	0x53, 0x2f, 0x70, 0x7e, 0x3a, 0x30, 0x72, 0x0e, 0x9c, 0x47, 0xc0, 0x0d, 0x45, 0xc9, 0xdd, 0xef,
	0x48, 0xd3, 0xe8, 0x7a, 0x2e, 0xfa, 0x5f, 0x06, 0x1d, 0x60, 0x35, 0x0d, 0x4a, 0x73, 0xf1, 0x03,
	0x53, 0x99, 0x90, 0x51, 0x10, 0x92, 0x77, 0xc7, 0x5e, 0xa0, 0x5c, 0x19, 0x5c, 0xcd, 0x4e, 0x15,
	0x2b, 0x4a, 0xa4, 0x2b, 0x28, 0x70, 0xba, 0x58, 0x8b, 0x7b, 0x20, 0x9a, 0xb6, 0xbd, 0x99, 0xc8,
	0xe2, 0xc1, 0xda, 0x78, 0xfa, 0xfa, 0x78, 0x05, 0x55, 0xe7, 0x12, 0x37, 0x15, 0x69, 0xcb, 0x17,
	0x6e, 0x28, 0x77, 0xbf, 0xc1, 0x9a, 0xb5, 0x51, 0xca, 0xb5, 0xe1, 0x1c, 0x26, 0x6f, 0xe3, 0x68,
	0x32, 0x21, 0x21, 0xf3, 0x9e, 0xa7, 0x32, 0x35, 0xae, 0xe6, 0x5c, 0xd9, 0x7a, 0xa1, 0xec, 0x3b,
	0x48, 0x8a, 0x38, 0xe9, 0x5d, 0xe5, 0x55, 0xa1, 0xa0, 0x6a, 0xe3, 0x3f, 0xee, 0xf6, 0x26, 0xd9,
	0x6b, 0x4f, 0xa1, 0x3c, 0x91, 0x5f, 0xca, 0x13, 0x23, 0x3e, 0x49, 0xe0, 0x17, 0x8f, 0x21, 0xf5,
	0x66, 0x66, 0xde, 0x9a, 0x7b, 0x8b, 0x25, 0xd3, 0x5e, 0x96, 0x4c, 0x5b, 0x2d, 0x19, 0xdc, 0x46,
	0x0c, 0x9e, 0x22, 0x06, 0xcf, 0x11, 0x83, 0x45, 0xc4, 0xe0, 0x35, 0x62, 0xf0, 0x1e, 0x31, 0x6d,
	0x15, 0x31, 0x78, 0x78, 0x63, 0x5a, 0xbf, 0xac, 0xfe, 0xd0, 0x83, 0x8f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x86, 0xa2, 0x96, 0x53, 0xb6, 0x03, 0x00, 0x00,
}
